### ISSUE TITLE
Issue mail cliente

### ISSUE THREAD

**Issue by fcancel** [7547-G2/HoyComoMobileApp#9]
Buenas tardes Carlos,

Ponganlos en castellano por favor. 
El descuento arriba de la imagen con fondo rojo no queda muy bien, quizás debajo de la imagen vaya mejor. En gral tenemos que revisar los estilos, material design, templates, y relacionado para la próxima iteración si es posible. 

Qué pasó con las historias de usuario, criterios y demás prototipos?

Saludos!

**Comment by carlosfurnari** [comment]
hecho
